import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PageShell, PageHeader } from "@/components/PageHeader";
import { Trophy, Search } from "lucide-react";
import { DOMAINS, CATEGORIES } from "@/lib/domains";
import { DomainCard } from "@/components/DomainCard";
import { SEED_ROADMAPS } from "@/lib/roadmap-catalog";

export const Route = createFileRoute("/_app/resources")({
  head: () => ({ meta: [{ title: "Resources Hub — ProjectSpark" }] }),
  component: Resources,
});

function Resources() {
  const [q, setQ] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  // Filters domains based on search query (matching name, category, blurb, tags, or roadmap node titles)
  const filtered = DOMAINS.filter((d) => {
    const matchesCategory = !selectedCategory || d.category === selectedCategory;

    const searchLower = q.toLowerCase();
    const matchesQuery =
      !q ||
      d.name.toLowerCase().includes(searchLower) ||
      d.category.toLowerCase().includes(searchLower) ||
      d.blurb.toLowerCase().includes(searchLower) ||
      d.tags.some((t) => t.toLowerCase().includes(searchLower)) ||
      // Match nodes in seeded roadmaps for this domain
      (SEED_ROADMAPS[d.slug] &&
        Object.values(SEED_ROADMAPS[d.slug]).some((tier) =>
          tier.nodes.some(
            (n) =>
              n.title.toLowerCase().includes(searchLower) ||
              n.why.toLowerCase().includes(searchLower),
          ),
        ));

    return matchesCategory && matchesQuery;
  });

  return (
    <PageShell>
      <PageHeader
        icon={Trophy}
        title="Learning Resources & Tracks"
        description="Explore interactive roadmaps across 100+ specialized engineering & science tracks. Generated by AI and tracked with real-time progress."
        actions={
          <div className="hidden items-center gap-2 rounded-xl border border-white/5 bg-white/5 px-3 py-1.5 text-xs text-muted-foreground sm:flex">
            <span>Press</span>
            <kbd className="rounded bg-background px-1.5 py-0.5 font-mono text-[10px] text-foreground border border-white/10">
              Ctrl
            </kbd>
            <span>+</span>
            <kbd className="rounded bg-background px-1.5 py-0.5 font-mono text-[10px] text-foreground border border-white/10">
              K
            </kbd>
            <span>to search globally</span>
          </div>
        }
      />

      <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-center">
        <div className="relative flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search learning paths, skills, or topics (e.g. Hooks, Sklearn)..."
            className="w-full rounded-xl border border-border bg-card/60 pl-9 pr-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-ring"
          />
        </div>
        <div
          className="flex flex-wrap gap-1.5 pr-1 max-h-[120px] overflow-y-auto md:max-h-none md:overflow-visible"
          data-lenis-prevent
        >
          <button
            onClick={() => setSelectedCategory(null)}
            className={`rounded-full border px-3 py-1 text-xs transition ${
              !selectedCategory
                ? "border-spark bg-spark/15 text-foreground"
                : "border-border text-muted-foreground hover:text-foreground"
            }`}
          >
            All
          </button>
          {CATEGORIES.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`rounded-full border px-3 py-1 text-xs transition ${
                selectedCategory === cat
                  ? "border-spark bg-spark/15 text-foreground"
                  : "border-border text-muted-foreground hover:text-foreground"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {filtered.map((d) => (
          <DomainCard key={d.slug} {...d} />
        ))}
        {filtered.length === 0 && (
          <div className="col-span-full py-16 text-center text-sm text-muted-foreground glass rounded-3xl">
            <Trophy className="mx-auto h-8 w-8 text-spark/60 animate-bounce mb-3" />
            <p className="text-base font-medium text-foreground">No tracks match your query</p>
            <p className="mt-1 text-xs">Try searching for other general skills or press Ctrl+K.</p>
          </div>
        )}
      </div>
    </PageShell>
  );
}
