/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppStudyGuideRouteImport } from './routes/_app.study-guide'
import { Route as AppStartupRouteImport } from './routes/_app.startup'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppResumeRouteImport } from './routes/_app.resume'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppResearchRouteImport } from './routes/_app.research'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppMentorRouteImport } from './routes/_app.mentor'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppLearningRouteImport } from './routes/_app.learning'
import { Route as AppJobPrepRouteImport } from './routes/_app.job-prep'
import { Route as AppInternshipsRouteImport } from './routes/_app.internships'
import { Route as AppGeneratorRouteImport } from './routes/_app.generator'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCollaborationRouteImport } from './routes/_app.collaboration'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBuilderRouteImport } from './routes/_app.builder'
import { Route as AppBuildYourOwnXRouteImport } from './routes/_app.build-your-own-x'
import { Route as AppBooksRouteImport } from './routes/_app.books'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppSavedIndexRouteImport } from './routes/_app.saved.index'
import { Route as AppRoadmapIndexRouteImport } from './routes/_app.roadmap.index'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppSavedProjectIdRouteImport } from './routes/_app.saved.$projectId'
import { Route as AppRoadmapSlugRouteImport } from './routes/_app.roadmap.$slug'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyGuideRoute = AppStudyGuideRouteImport.update({
  id: '/study-guide',
  path: '/study-guide',
  getParentRoute: () => AppRoute,
} as any)
const AppStartupRoute = AppStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppJobPrepRoute = AppJobPrepRouteImport.update({
  id: '/job-prep',
  path: '/job-prep',
  getParentRoute: () => AppRoute,
} as any)
const AppInternshipsRoute = AppInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCollaborationRoute = AppCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildYourOwnXRoute = AppBuildYourOwnXRouteImport.update({
  id: '/build-your-own-x',
  path: '/build-your-own-x',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIndexRoute = AppSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapIndexRoute = AppRoadmapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoadmapRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppSavedProjectIdRoute = AppSavedProjectIdRouteImport.update({
  id: '/saved/$projectId',
  path: '/saved/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapSlugRoute = AppRoadmapSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRoadmapRoute,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/about': typeof AppAboutRoute
  '/analytics': typeof AppAnalyticsRoute
  '/books': typeof AppBooksRoute
  '/build-your-own-x': typeof AppBuildYourOwnXRoute
  '/builder': typeof AppBuilderRoute
  '/chat': typeof AppChatRouteWithChildren
  '/collaboration': typeof AppCollaborationRoute
  '/dashboard': typeof AppDashboardRoute
  '/generator': typeof AppGeneratorRoute
  '/internships': typeof AppInternshipsRoute
  '/job-prep': typeof AppJobPrepRoute
  '/learning': typeof AppLearningRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/mentor': typeof AppMentorRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/research': typeof AppResearchRoute
  '/resources': typeof AppResourcesRoute
  '/resume': typeof AppResumeRoute
  '/roadmap': typeof AppRoadmapRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/startup': typeof AppStartupRoute
  '/study-guide': typeof AppStudyGuideRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/roadmap/$slug': typeof AppRoadmapSlugRoute
  '/saved/$projectId': typeof AppSavedProjectIdRoute
  '/chat/': typeof AppChatIndexRoute
  '/roadmap/': typeof AppRoadmapIndexRoute
  '/saved/': typeof AppSavedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/about': typeof AppAboutRoute
  '/analytics': typeof AppAnalyticsRoute
  '/books': typeof AppBooksRoute
  '/build-your-own-x': typeof AppBuildYourOwnXRoute
  '/builder': typeof AppBuilderRoute
  '/collaboration': typeof AppCollaborationRoute
  '/dashboard': typeof AppDashboardRoute
  '/generator': typeof AppGeneratorRoute
  '/internships': typeof AppInternshipsRoute
  '/job-prep': typeof AppJobPrepRoute
  '/learning': typeof AppLearningRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/mentor': typeof AppMentorRoute
  '/portfolio': typeof AppPortfolioRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/research': typeof AppResearchRoute
  '/resources': typeof AppResourcesRoute
  '/resume': typeof AppResumeRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/startup': typeof AppStartupRoute
  '/study-guide': typeof AppStudyGuideRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/roadmap/$slug': typeof AppRoadmapSlugRoute
  '/saved/$projectId': typeof AppSavedProjectIdRoute
  '/chat': typeof AppChatIndexRoute
  '/roadmap': typeof AppRoadmapIndexRoute
  '/saved': typeof AppSavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/books': typeof AppBooksRoute
  '/_app/build-your-own-x': typeof AppBuildYourOwnXRoute
  '/_app/builder': typeof AppBuilderRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/collaboration': typeof AppCollaborationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/generator': typeof AppGeneratorRoute
  '/_app/internships': typeof AppInternshipsRoute
  '/_app/job-prep': typeof AppJobPrepRoute
  '/_app/learning': typeof AppLearningRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/mentor': typeof AppMentorRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/resume': typeof AppResumeRoute
  '/_app/roadmap': typeof AppRoadmapRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/startup': typeof AppStartupRoute
  '/_app/study-guide': typeof AppStudyGuideRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
  '/_app/roadmap/$slug': typeof AppRoadmapSlugRoute
  '/_app/saved/$projectId': typeof AppSavedProjectIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/roadmap/': typeof AppRoadmapIndexRoute
  '/_app/saved/': typeof AppSavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/about'
    | '/analytics'
    | '/books'
    | '/build-your-own-x'
    | '/builder'
    | '/chat'
    | '/collaboration'
    | '/dashboard'
    | '/generator'
    | '/internships'
    | '/job-prep'
    | '/learning'
    | '/marketplace'
    | '/mentor'
    | '/portfolio'
    | '/profile'
    | '/progress'
    | '/research'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/settings'
    | '/skills'
    | '/startup'
    | '/study-guide'
    | '/api/chat'
    | '/chat/$threadId'
    | '/roadmap/$slug'
    | '/saved/$projectId'
    | '/chat/'
    | '/roadmap/'
    | '/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/about'
    | '/analytics'
    | '/books'
    | '/build-your-own-x'
    | '/builder'
    | '/collaboration'
    | '/dashboard'
    | '/generator'
    | '/internships'
    | '/job-prep'
    | '/learning'
    | '/marketplace'
    | '/mentor'
    | '/portfolio'
    | '/profile'
    | '/progress'
    | '/research'
    | '/resources'
    | '/resume'
    | '/settings'
    | '/skills'
    | '/startup'
    | '/study-guide'
    | '/api/chat'
    | '/chat/$threadId'
    | '/roadmap/$slug'
    | '/saved/$projectId'
    | '/chat'
    | '/roadmap'
    | '/saved'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/about'
    | '/_app/analytics'
    | '/_app/books'
    | '/_app/build-your-own-x'
    | '/_app/builder'
    | '/_app/chat'
    | '/_app/collaboration'
    | '/_app/dashboard'
    | '/_app/generator'
    | '/_app/internships'
    | '/_app/job-prep'
    | '/_app/learning'
    | '/_app/marketplace'
    | '/_app/mentor'
    | '/_app/portfolio'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/research'
    | '/_app/resources'
    | '/_app/resume'
    | '/_app/roadmap'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/startup'
    | '/_app/study-guide'
    | '/api/chat'
    | '/_app/chat/$threadId'
    | '/_app/roadmap/$slug'
    | '/_app/saved/$projectId'
    | '/_app/chat/'
    | '/_app/roadmap/'
    | '/_app/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/study-guide': {
      id: '/_app/study-guide'
      path: '/study-guide'
      fullPath: '/study-guide'
      preLoaderRoute: typeof AppStudyGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/startup': {
      id: '/_app/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof AppStartupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentor': {
      id: '/_app/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning': {
      id: '/_app/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-prep': {
      id: '/_app/job-prep'
      path: '/job-prep'
      fullPath: '/job-prep'
      preLoaderRoute: typeof AppJobPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/internships': {
      id: '/_app/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof AppInternshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator': {
      id: '/_app/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration': {
      id: '/_app/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof AppCollaborationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build-your-own-x': {
      id: '/_app/build-your-own-x'
      path: '/build-your-own-x'
      fullPath: '/build-your-own-x'
      preLoaderRoute: typeof AppBuildYourOwnXRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books': {
      id: '/_app/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/': {
      id: '/_app/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof AppSavedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap/': {
      id: '/_app/roadmap/'
      path: '/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof AppRoadmapIndexRouteImport
      parentRoute: typeof AppRoadmapRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/saved/$projectId': {
      id: '/_app/saved/$projectId'
      path: '/saved/$projectId'
      fullPath: '/saved/$projectId'
      preLoaderRoute: typeof AppSavedProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap/$slug': {
      id: '/_app/roadmap/$slug'
      path: '/$slug'
      fullPath: '/roadmap/$slug'
      preLoaderRoute: typeof AppRoadmapSlugRouteImport
      parentRoute: typeof AppRoadmapRoute
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatThreadIdRoute: AppChatThreadIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRoadmapRouteChildren {
  AppRoadmapSlugRoute: typeof AppRoadmapSlugRoute
  AppRoadmapIndexRoute: typeof AppRoadmapIndexRoute
}

const AppRoadmapRouteChildren: AppRoadmapRouteChildren = {
  AppRoadmapSlugRoute: AppRoadmapSlugRoute,
  AppRoadmapIndexRoute: AppRoadmapIndexRoute,
}

const AppRoadmapRouteWithChildren = AppRoadmapRoute._addFileChildren(
  AppRoadmapRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAboutRoute: typeof AppAboutRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBooksRoute: typeof AppBooksRoute
  AppBuildYourOwnXRoute: typeof AppBuildYourOwnXRoute
  AppBuilderRoute: typeof AppBuilderRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppCollaborationRoute: typeof AppCollaborationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppInternshipsRoute: typeof AppInternshipsRoute
  AppJobPrepRoute: typeof AppJobPrepRoute
  AppLearningRoute: typeof AppLearningRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMentorRoute: typeof AppMentorRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppResearchRoute: typeof AppResearchRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppResumeRoute: typeof AppResumeRoute
  AppRoadmapRoute: typeof AppRoadmapRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppStartupRoute: typeof AppStartupRoute
  AppStudyGuideRoute: typeof AppStudyGuideRoute
  AppSavedProjectIdRoute: typeof AppSavedProjectIdRoute
  AppSavedIndexRoute: typeof AppSavedIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAboutRoute: AppAboutRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBooksRoute: AppBooksRoute,
  AppBuildYourOwnXRoute: AppBuildYourOwnXRoute,
  AppBuilderRoute: AppBuilderRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppCollaborationRoute: AppCollaborationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppInternshipsRoute: AppInternshipsRoute,
  AppJobPrepRoute: AppJobPrepRoute,
  AppLearningRoute: AppLearningRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMentorRoute: AppMentorRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppResearchRoute: AppResearchRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppResumeRoute: AppResumeRoute,
  AppRoadmapRoute: AppRoadmapRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppStartupRoute: AppStartupRoute,
  AppStudyGuideRoute: AppStudyGuideRoute,
  AppSavedProjectIdRoute: AppSavedProjectIdRoute,
  AppSavedIndexRoute: AppSavedIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
